### ISSUE TITLE
Array.prototype.find()

### ISSUE THREAD

**Issue by ianks** [indiesquidge/sales_engine_js#1]
I'll just leave this here.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by indiesquidge** [comment]
@ianks I was trying to avoid ES6 on my first go through, and then go back and implement it where I felt pain points (like with this). But I appreciate the participation :)

**Comment by ianks** [comment]
is that an es6 method? i thought that had been around for awhile.

**Comment by indiesquidge** [comment]
Yeah it is. You'll notice it's flagged with the green box and test tube at the top.
